import type { RuntimeProvider } from '../types.js';
import { QWEN_CLOUD_MODELS, QWEN_CODING_MODELS } from './qwen-models.js';

export const RUNTIME_PROVIDERS: RuntimeProvider[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    baseURL: 'https://api.openai.com/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'OPENAI_API_KEY',
    icon: '🤖',
    description: "OpenAI's official API",
    docsUrl: 'https://platform.openai.com',
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        description: 'Flagship model with vision',
        default: true,
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        description: 'Faster, more cost-effective model',
      },
      {
        id: 'gpt-4.1',
        name: 'GPT-4.1',
        description: 'Improved coding and long-context GPT-4',
      },
      {
        id: 'gpt-4.1-mini',
        name: 'GPT-4.1 Mini',
        description: 'Smaller GPT-4.1',
      },
      {
        id: 'gpt-4.1-nano',
        name: 'GPT-4.1 Nano',
        description: 'Lowest-latency GPT-4.1',
      },
      {
        id: 'o3',
        name: 'o3',
        description: 'Reasoning model for complex tasks',
      },
      {
        id: 'o3-mini',
        name: 'o3 Mini',
        description: 'Compact reasoning model',
      },
      {
        id: 'o4-mini',
        name: 'o4 Mini',
        description: 'Fast reasoning model',
      },
      {
        id: 'gpt-4-turbo',
        name: 'GPT-4 Turbo',
        description: 'Optimized version of GPT-4',
      },
      {
        id: 'gpt-3.5-turbo',
        name: 'GPT-3.5 Turbo',
        description: 'Efficient, lower-cost model',
      },
    ],
  },
  {
    id: 'nebius',
    name: 'Nebius Token Factory',
    baseURL: 'https://api.nebius.com',
    endpoint: '/ai/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'NEBIUS_API_KEY',
    icon: '⭐',
    description: 'AI infrastructure platform with token-based billing',
    docsUrl: 'https://docs.nebius.com',
    models: [
      {
        id: 'yandexgpt',
        name: 'Yandex GPT',
        description: "Yandex's general-purpose language model",
        default: true,
      },
      {
        id: 'yandexgpt-lite',
        name: 'Yandex GPT Lite',
        description: 'Faster, more efficient version of Yandex GPT',
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        description: "OpenAI's fast, cost-effective model via Nebius",
      },
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        description: "OpenAI's latest flagship model via Nebius",
      },
      {
        id: 'claude-3-5-sonnet',
        name: 'Claude 3.5 Sonnet',
        description: "Anthropic's balanced model via Nebius",
      },
      {
        id: 'claude-3-haiku',
        name: 'Claude 3 Haiku',
        description: "Anthropic's fastest model via Nebius",
      },
    ],
  },
  {
    id: 'poe',
    name: 'Poe',
    baseURL: 'https://poe.com/api',
    requiresAuth: true,
    apiKeyEnvVar: 'POE_API_KEY',
    icon: '🎯',
    description: 'Chatbot platform with access to multiple models',
    docsUrl: 'https://poe.com',
    models: [
      {
        id: 'claude-3-5-sonnet',
        name: 'Claude 3.5 Sonnet',
        description: "Anthropic's state-of-the-art model",
        default: true,
      },
      {
        id: 'claude-3-opus',
        name: 'Claude 3 Opus',
        description: 'Most powerful Claude model',
      },
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        description: "OpenAI's latest flagship model",
      },
      {
        id: 'gpt-4-turbo',
        name: 'GPT-4 Turbo',
        description: 'Optimized version of GPT-4',
      },
      {
        id: 'llama-3.1-70b',
        name: 'Llama 3.1 70B',
        description: "Meta's latest open model",
      },
      {
        id: 'mistral-large',
        name: 'Mistral Large',
        description: "Mistral's top-tier model",
      },
      {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        description: "Google's advanced model",
      },
    ],
  },
  {
    id: 'search',
    name: 'Search',
    baseURL: 'https://api.search.ai',
    requiresAuth: true,
    apiKeyEnvVar: 'SEARCH_API_KEY',
    icon: '🔍',
    description: 'Search-based AI platform',
    models: [
      {
        id: 'search-70b',
        name: 'Search 70B',
        description: '70B parameter search-optimized model',
        default: true,
      },
      {
        id: 'search-400b',
        name: 'Search 400B',
        description: '400B parameter flagship model',
      },
      {
        id: 'search-v2',
        name: 'Search v2',
        description: 'Latest version of Search model',
      },
    ],
  },
  {
    id: 'helicone',
    name: 'Helicone',
    baseURL: 'https://api.helicone.ai',
    requiresAuth: true,
    apiKeyEnvVar: 'HELICONE_API_KEY',
    icon: '🚁',
    description: 'AI observability and proxy platform',
    docsUrl: 'https://helicone.ai',
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        default: true,
      },
      {
        id: 'gpt-4-turbo',
        name: 'GPT-4 Turbo',
      },
      {
        id: 'claude-3-5-sonnet',
        name: 'Claude 3.5 Sonnet',
      },
      {
        id: 'llama-3.1-70b',
        name: 'Llama 3.1 70B',
      },
      {
        id: 'mistral-large',
        name: 'Mistral Large',
      },
    ],
  },
  {
    id: 'ollama-cloud',
    name: 'Ollama Cloud',
    baseURL: 'https://cloud.ollama.ai',
    requiresAuth: true,
    apiKeyEnvVar: 'OLLAMA_CLOUD_API_KEY',
    icon: '☁️',
    description: 'Cloud-hosted open-source models',
    docsUrl: 'https://ollama.ai',
    models: [
      {
        id: 'llama3.1-70b',
        name: 'Llama 3.1 70B',
        description: "Meta's latest open model",
        default: true,
      },
      {
        id: 'llama3.1-8b',
        name: 'Llama 3.1 8B',
        description: 'Smaller, faster Llama 3.1 variant',
      },
      {
        id: 'mistral-large',
        name: 'Mistral Large',
        description: "Mistral's large model",
      },
      {
        id: 'phi-3.5-mini',
        name: 'Phi 3.5 Mini',
        description: "Microsoft's lightweight model",
      },
      {
        id: 'qwen2.5-coder-7b',
        name: 'Qwen 2.5 Coder 7B',
        description: "Alibaba's code-specialized model",
      },
      {
        id: 'gemma-7b',
        name: 'Gemma 7B',
        description: "Google's open model",
      },
    ],
  },
  {
    id: 'z-ai-coding',
    name: 'Z.AI Coding Plan',
    baseURL: 'https://api.z.ai',
    requiresAuth: true,
    apiKeyEnvVar: 'ZAI_API_KEY',
    icon: '💎',
    description: 'AI coding assistant platform',
    docsUrl: 'https://z.ai',
    models: [
      {
        id: 'z-coder-32k',
        name: 'Z Coder 32K',
        description: '32K context coding model',
        default: true,
      },
      {
        id: 'z-coder-128k',
        name: 'Z Coder 128K',
        description: '128K context coding model',
      },
      {
        id: 'z-pro',
        name: 'Z Pro',
        description: 'Professional coding assistant',
      },
    ],
  },
  {
    id: 'bedrock',
    name: 'Amazon Bedrock',
    baseURL: 'https://bedrock-runtime.us-east-1.amazonaws.com',
    requiresAuth: true,
    apiKeyEnvVar: 'AWS_ACCESS_KEY_ID',
    icon: '🏗️',
    description: 'AWS AI model platform',
    docsUrl: 'https://aws.amazon.com/bedrock',
    models: [
      {
        id: 'anthropic.claude-3-5-sonnet-20241022-v2:0',
        name: 'Claude 3.5 Sonnet v2',
        description: "Anthropic's latest Sonnet model",
        default: true,
      },
      {
        id: 'anthropic.claude-3-opus-20240229-v1:0',
        name: 'Claude 3 Opus',
        description: "Anthropic's most powerful model",
      },
      {
        id: 'anthropic.claude-3-sonnet-20240229-v1:0',
        name: 'Claude 3 Sonnet',
        description: "Anthropic's balanced model",
      },
      {
        id: 'meta.llama3-1-70b-instruct-v1:0',
        name: 'Llama 3.1 70B Instruct',
        description: "Meta's latest instruct model",
      },
      {
        id: 'meta.llama3-1-8b-instruct-v1:0',
        name: 'Llama 3.1 8B Instruct',
        description: 'Lightweight Llama 3.1 model',
      },
      {
        id: 'mistral.mistral-large-2407-v1:0',
        name: 'Mistral Large',
        description: "Mistral's large model",
      },
      {
        id: 'mistral.mixtral-8x7b-instruct-v0:1',
        name: 'Mixtral 8x7B Instruct',
        description: "Mistral's mixture of experts model",
      },
      {
        id: 'cohere.command-r-plus-v1:0',
        name: 'Command R+',
        description: "Cohere's advanced model",
      },
      {
        id: 'ai21.j2-ultra-v1',
        name: 'Jurassic-2 Ultra',
        description: "AI21's ultra model",
      },
    ],
  },
  {
    id: 'the-grid',
    name: 'The Grid AI',
    baseURL: 'https://api.thegrid.ai',
    requiresAuth: true,
    apiKeyEnvVar: 'GRID_API_KEY',
    icon: '🔲',
    description: 'Decentralized AI network',
    docsUrl: 'https://thegrid.ai',
    models: [
      {
        id: 'grid-70b',
        name: 'Grid 70B',
        description: '70B parameter Grid model',
        default: true,
      },
      {
        id: 'grid-8b',
        name: 'Grid 8B',
        description: '8B parameter Grid model',
      },
    ],
  },
  {
    id: 'baseten',
    name: 'Baseten',
    baseURL: 'https://app.baseten.co/api',
    requiresAuth: true,
    apiKeyEnvVar: 'BASETEN_API_KEY',
    icon: '🏢',
    description: 'Model deployment and inference platform',
    docsUrl: 'https://baseten.co',
    models: [
      {
        id: 'auto',
        name: 'Auto (Deployed Models)',
        description: 'Your deployed models on Baseten',
        default: true,
      },
    ],
  },
  {
    id: 'frogbot',
    name: 'FrogBot',
    baseURL: 'https://api.frogbot.ai',
    requiresAuth: true,
    apiKeyEnvVar: 'FROGBOT_API_KEY',
    icon: '🐸',
    description: 'AI model gateway and router',
    docsUrl: 'https://frogbot.ai',
    models: [
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
        description: 'Cost-effective OpenAI model',
        default: true,
      },
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        description: "OpenAI's flagship model",
      },
      {
        id: 'claude-3-5-sonnet',
        name: 'Claude 3.5 Sonnet',
        description: "Anthropic's state-of-the-art model",
      },
      {
        id: 'llama-3.1-70b',
        name: 'Llama 3.1 70B',
        description: "Meta's open model",
      },
    ],
  },
  {
    id: 'zhipu',
    name: 'Zhipu AI Coding Plan',
    baseURL: 'https://open.bigmodel.cn',
    requiresAuth: true,
    apiKeyEnvVar: 'ZHIPU_API_KEY',
    icon: '🧩',
    description: 'Chinese AI model provider with coding focus',
    docsUrl: 'https://bigmodel.cn',
    models: [
      {
        id: 'glm-4-flash',
        name: 'GLM-4 Flash',
        description: 'Fast, efficient coding model',
        default: true,
      },
      {
        id: 'glm-4',
        name: 'GLM-4',
        description: "Zhipu's flagship model",
      },
      {
        id: 'glm-4-air',
        name: 'GLM-4 Air',
        description: 'Lightweight, fast model',
      },
      {
        id: 'codegeex4',
        name: 'CodeGeeX4',
        description: 'Coding-specialized model',
      },
    ],
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    baseURL: 'http://localhost:1234/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '💻',
    description: 'Local LM Studio inference server',
    docsUrl: 'http://127.0.0.1:1234',
    models: [], // Will be fetched dynamically
  },
  {
    id: 'ollama',
    name: 'Ollama',
    baseURL: 'http://localhost:11434/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🦙',
    description: 'Local Ollama model runner & API server',
    docsUrl: 'https://ollama.com',
    models: [],
  },
  {
    id: 'foundry-local',
    name: 'Foundry Local',
    baseURL: 'http://localhost:5272/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🏗️',
    description: 'Microsoft Azure AI Foundry Local Engine',
    docsUrl: 'https://ai.azure.com',
    models: [],
  },
  {
    id: 'llamacpp',
    name: 'llama.cpp',
    baseURL: 'http://localhost:8080/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🦙',
    description: 'Local llama.cpp HTTP server (OpenAI compatible)',
    docsUrl: 'https://github.com/ggerganov/llama.cpp',
    models: [],
  },
  {
    id: 'fastflowlm',
    name: 'FastFlowLM',
    baseURL: 'http://localhost:8000/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '⚡',
    description: 'High-efficiency FastFlowLM local runtime',
    docsUrl: 'https://github.com/fastflowlm',
    models: [],
  },
  {
    id: 'vllm',
    name: 'vLLM',
    baseURL: 'http://localhost:8000/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🚀',
    description: 'High-throughput local vLLM inference server',
    docsUrl: 'https://github.com/vllm-project/vllm',
    models: [],
  },
  {
    id: 'jan',
    name: 'Jan',
    baseURL: 'http://localhost:1337/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🤖',
    description: 'Open-source local AI desktop assistant & server',
    docsUrl: 'https://jan.ai',
    models: [],
  },
  {
    id: 'localai',
    name: 'LocalAI',
    baseURL: 'http://localhost:8080/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🏡',
    description: 'Self-hosted local OpenAI alternative',
    docsUrl: 'https://localai.io',
    models: [],
  },
  {
    id: 'oobabooga',
    name: 'Text Generation WebUI',
    baseURL: 'http://localhost:5000/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '💬',
    description: 'oobabooga Text Generation WebUI OpenAI API server',
    docsUrl: 'https://github.com/oobabooga/text-generation-webui',
    models: [],
  },
  {
    id: 'sglang',
    name: 'SGLang',
    baseURL: 'http://localhost:30000/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🌀',
    description: 'Local SGLang OpenAI-compatible server',
    docsUrl: 'https://github.com/sgl-project/sglang',
    models: [],
  },
  {
    id: 'mlx',
    name: 'MLX',
    baseURL: 'http://localhost:8080/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🍎',
    description: 'Apple MLX lm server (OpenAI-compatible). Default port overlaps llama.cpp.',
    docsUrl: 'https://github.com/ml-explore/mlx-lm',
    models: [],
  },
  {
    id: 'koboldcpp',
    name: 'KoboldCpp',
    baseURL: 'http://localhost:5001/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🐉',
    description: 'KoboldCpp OpenAI-compatible API',
    docsUrl: 'https://github.com/LostRuins/koboldcpp',
    models: [],
  },
  {
    id: 'docker-model-runner',
    name: 'Docker Model Runner',
    baseURL: 'http://localhost:12434/engines/v1',
    requiresAuth: false,
    isLocal: true,
    dynamicModels: true,
    icon: '🐳',
    description: 'Docker Model Runner OpenAI-compatible API (enable host TCP on 12434)',
    docsUrl: 'https://docs.docker.com/ai/model-runner/',
    models: [],
  },
  {
    id: 'foundry',
    name: 'Azure AI Foundry',
    baseURL: '',
    requiresAuth: true,
    apiKeyEnvVar: 'AZURE_OPENAI_API_KEY',
    requiresCustomBaseURL: true,
    baseURLPlaceholder: 'https://YOUR-RESOURCE.openai.azure.com/openai/v1',
    endpointEnvVar: 'AZURE_OPENAI_ENDPOINT',
    hostPatterns: ['openai.azure.com', 'services.ai.azure.com'],
    dynamicModels: true,
    icon: '☁️',
    description: 'Azure AI Foundry / Azure OpenAI (per-resource OpenAI v1 endpoint)',
    docsUrl: 'https://learn.microsoft.com/azure/ai-foundry',
    models: [
      {
        id: 'gpt-4o',
        name: 'GPT-4o',
        description: 'Use your deployment name if it differs',
        default: true,
      },
      {
        id: 'gpt-4o-mini',
        name: 'GPT-4o Mini',
      },
      {
        id: 'gpt-4.1',
        name: 'GPT-4.1',
      },
    ],
  },
  {
    id: 'kimi-code',
    name: 'Kimi Code',
    baseURL: 'https://api.kimi.com/coding/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'KIMI_API_KEY',
    icon: '🌙',
    description: 'Moonshot Kimi Code membership (OpenAI-compatible coding API)',
    docsUrl: 'https://www.kimi.com/code/docs/en/',
    defaultHeaders: {
      'User-Agent': 'nanoagent/2.1.5',
    },
    models: [
      {
        id: 'kimi-for-coding',
        name: 'Kimi for Coding',
        description: 'Kimi K2.7 Code — available to all members',
        default: true,
      },
      {
        id: 'kimi-for-coding-highspeed',
        name: 'Kimi for Coding HighSpeed',
        description: 'Faster coding tier (Allegretto+)',
      },
      {
        id: 'k3',
        name: 'Kimi K3',
        description: 'Up to 1M context (tier-gated); low/high/max thinking',
      },
      {
        id: 'k3-256k',
        name: 'Kimi K3 256K',
        description: 'Same quality as K3 within 256k, lower quota',
      },
    ],
  },
  {
    id: 'dashscope',
    name: 'Alibaba Model Studio',
    baseURL: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'DASHSCOPE_API_KEY',
    icon: '☁️',
    description: 'Alibaba Cloud Model Studio (International / Singapore, pay-as-you-go Qwen)',
    docsUrl: 'https://help.aliyun.com/en/model-studio/base-url',
    models: QWEN_CLOUD_MODELS,
  },
  {
    id: 'dashscope-cn',
    name: 'Alibaba Model Studio (China)',
    baseURL: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'DASHSCOPE_CN_API_KEY',
    icon: '☁️',
    description: 'Alibaba Cloud Model Studio China (Beijing) pay-as-you-go Qwen',
    docsUrl: 'https://help.aliyun.com/en/model-studio/base-url',
    models: QWEN_CLOUD_MODELS,
  },
  {
    id: 'dashscope-coding',
    name: 'Alibaba Coding Plan',
    baseURL: 'https://coding-intl.dashscope.aliyuncs.com/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'DASHSCOPE_CODING_API_KEY',
    icon: '💎',
    description: 'Alibaba Coding Plan (International). Use sk-sp- keys, not pay-as-you-go keys.',
    docsUrl: 'https://www.alibabacloud.com/help/en/model-studio/coding-plan',
    models: QWEN_CODING_MODELS,
  },
  {
    id: 'dashscope-coding-cn',
    name: 'Alibaba Coding Plan (China)',
    baseURL: 'https://coding.dashscope.aliyuncs.com/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'DASHSCOPE_CODING_CN_API_KEY',
    icon: '💎',
    description: 'Alibaba Coding Plan (China). Use sk-sp- keys, not pay-as-you-go keys.',
    docsUrl: 'https://help.aliyun.com/en/model-studio/coding-plan',
    models: QWEN_CODING_MODELS,
  },
  {
    id: 'moonshot',
    name: 'Moonshot',
    baseURL: 'https://api.moonshot.ai/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'MOONSHOT_API_KEY',
    icon: '🌙',
    description: 'Moonshot / Kimi Platform (International, pay-as-you-go)',
    docsUrl: 'https://platform.moonshot.ai',
    models: [
      {
        id: 'kimi-k2.5',
        name: 'Kimi K2.5',
        description: 'Moonshot flagship Kimi model',
        default: true,
      },
      {
        id: 'moonshot-v1-auto',
        name: 'Moonshot v1 Auto',
        description: 'Auto-routed Moonshot model',
      },
      {
        id: 'kimi-latest',
        name: 'Kimi Latest',
        description: 'Latest Kimi snapshot',
      },
    ],
  },
  {
    id: 'moonshot-cn',
    name: 'Moonshot (China)',
    baseURL: 'https://api.moonshot.cn/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'MOONSHOT_CN_API_KEY',
    icon: '🌙',
    description: 'Moonshot / Kimi Platform (China, pay-as-you-go)',
    docsUrl: 'https://platform.moonshot.cn',
    models: [
      {
        id: 'kimi-k2.5',
        name: 'Kimi K2.5',
        description: 'Moonshot flagship Kimi model',
        default: true,
      },
      {
        id: 'moonshot-v1-auto',
        name: 'Moonshot v1 Auto',
        description: 'Auto-routed Moonshot model',
      },
      {
        id: 'kimi-latest',
        name: 'Kimi Latest',
        description: 'Latest Kimi snapshot',
      },
    ],
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    baseURL: 'https://api.deepseek.com',
    requiresAuth: true,
    apiKeyEnvVar: 'DEEPSEEK_API_KEY',
    icon: '🐋',
    description: "DeepSeek's official OpenAI-compatible API",
    docsUrl: 'https://api-docs.deepseek.com',
    models: [
      {
        id: 'deepseek-chat',
        name: 'DeepSeek Chat',
        description: 'DeepSeek non-reasoning chat model',
        default: true,
      },
      {
        id: 'deepseek-reasoner',
        name: 'DeepSeek Reasoner',
        description: 'DeepSeek reasoning model',
      },
    ],
  },
  {
    id: 'groq',
    name: 'Groq',
    baseURL: 'https://api.groq.com/openai/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'GROQ_API_KEY',
    icon: '⚡',
    description: 'Groq LPU inference (OpenAI-compatible)',
    docsUrl: 'https://console.groq.com',
    defaultRpm: 30,
    defaultMaxInFlight: 2,
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        name: 'Llama 3.3 70B',
        description: 'Meta Llama 3.3 70B on Groq',
        default: true,
      },
      {
        id: 'llama-3.1-8b-instant',
        name: 'Llama 3.1 8B Instant',
        description: 'Fast 8B Llama on Groq',
      },
      {
        id: 'qwen/qwen3-32b',
        name: 'Qwen3 32B',
        description: 'Qwen3 32B on Groq',
      },
    ],
  },
  {
    id: 'xai',
    name: 'xAI',
    baseURL: 'https://api.x.ai/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'XAI_API_KEY',
    icon: '𝕏',
    description: 'xAI Grok models',
    docsUrl: 'https://docs.x.ai',
    models: [
      {
        id: 'grok-4',
        name: 'Grok 4',
        description: 'xAI flagship Grok',
        default: true,
      },
      {
        id: 'grok-3',
        name: 'Grok 3',
        description: 'Previous Grok flagship',
      },
      {
        id: 'grok-3-mini',
        name: 'Grok 3 Mini',
        description: 'Faster, cheaper Grok',
      },
    ],
  },
  {
    id: 'together',
    name: 'Together',
    baseURL: 'https://api.together.xyz/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'TOGETHER_API_KEY',
    icon: '🤝',
    description: 'Together Inference (OpenAI-compatible)',
    docsUrl: 'https://docs.together.ai',
    models: [
      {
        id: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
        name: 'Llama 3.3 70B Turbo',
        default: true,
      },
      {
        id: 'Qwen/Qwen2.5-Coder-32B-Instruct',
        name: 'Qwen2.5 Coder 32B',
      },
    ],
  },
  {
    id: 'fireworks',
    name: 'Fireworks',
    baseURL: 'https://api.fireworks.ai/inference/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'FIREWORKS_API_KEY',
    icon: '🎆',
    description: 'Fireworks AI inference',
    docsUrl: 'https://docs.fireworks.ai',
    models: [
      {
        id: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
        name: 'Llama 3.3 70B',
        default: true,
      },
      {
        id: 'accounts/fireworks/models/qwen2p5-coder-32b-instruct',
        name: 'Qwen2.5 Coder 32B',
      },
    ],
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    baseURL: 'https://api.cerebras.ai/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'CEREBRAS_API_KEY',
    icon: '🧠',
    description: 'Cerebras inference (OpenAI-compatible)',
    docsUrl: 'https://inference-docs.cerebras.ai',
    defaultRpm: 30,
    defaultMaxInFlight: 2,
    models: [
      {
        id: 'llama3.1-8b',
        name: 'Llama 3.1 8B',
        default: true,
      },
      {
        id: 'llama3.3-70b',
        name: 'Llama 3.3 70B',
      },
      {
        id: 'qwen-3-32b',
        name: 'Qwen 3 32B',
      },
    ],
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    baseURL: 'https://api.minimax.io/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'MINIMAX_API_KEY',
    icon: '🅰️',
    description: 'MiniMax OpenAI-compatible API (intl). China: api.minimaxi.com',
    docsUrl: 'https://platform.minimax.io/docs/api-reference/text-openai-api',
    models: [
      {
        id: 'MiniMax-M2.7',
        name: 'MiniMax M2.7',
        description: 'Agentic coding model',
        default: true,
      },
      {
        id: 'MiniMax-M2.5',
        name: 'MiniMax M2.5',
      },
      {
        id: 'MiniMax-M3',
        name: 'MiniMax M3',
      },
    ],
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    baseURL: 'https://integrate.api.nvidia.com/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'NVIDIA_API_KEY',
    dynamicModels: true,
    icon: '🟢',
    description: 'NVIDIA NIM / build.nvidia.com OpenAI-compatible API',
    docsUrl: 'https://build.nvidia.com',
    models: [
      {
        id: 'meta/llama-3.1-8b-instruct',
        name: 'Llama 3.1 8B Instruct',
        default: true,
      },
      {
        id: 'meta/llama-3.1-70b-instruct',
        name: 'Llama 3.1 70B Instruct',
      },
      {
        id: 'qwen/qwen2.5-coder-32b-instruct',
        name: 'Qwen2.5 Coder 32B',
      },
    ],
  },
  {
    id: 'gmi-cloud',
    name: 'GMI Cloud',
    baseURL: 'https://api.gmi-serving.com/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'GMI_API_KEY',
    dynamicModels: true,
    icon: '🌩️',
    description: 'GMI Cloud GPU inference (OpenAI-compatible)',
    docsUrl: 'https://docs.gmicloud.ai',
    models: [
      {
        id: 'meta-llama/Llama-3.3-70B-Instruct',
        name: 'Llama 3.3 70B Instruct',
        description: "Meta's open instruct model on GMI",
        default: true,
      },
      {
        id: 'deepseek-ai/DeepSeek-V4-Pro',
        name: 'DeepSeek V4 Pro',
        description: 'DeepSeek flagship on GMI',
      },
    ],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    baseURL: 'https://router.huggingface.co/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'HUGGINGFACE_API_KEY',
    apiKeyEnvAliases: ['HF_TOKEN'],
    dynamicModels: true,
    icon: '🤗',
    description: 'Hugging Face Inference Providers (OpenAI-compatible router)',
    docsUrl: 'https://huggingface.co/docs/inference-providers',
    defaultRpm: 15,
    defaultMaxInFlight: 1,
    models: [],
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    baseURL: 'https://api.anthropic.com/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'ANTHROPIC_API_KEY',
    icon: '🦭',
    description: "Anthropic's Claude models",
    docsUrl: 'https://anthropic.com',
    models: [
      {
        id: 'claude-3-5-sonnet-20241022',
        name: 'Claude 3.5 Sonnet',
        description: 'Latest Sonnet model',
        default: true,
      },
      {
        id: 'claude-3-opus-20240229',
        name: 'Claude 3 Opus',
        description: 'Most powerful Claude model',
      },
      {
        id: 'claude-3-sonnet-20240229',
        name: 'Claude 3 Sonnet',
        description: 'Balanced model for most tasks',
      },
      {
        id: 'claude-3-haiku-20240307',
        name: 'Claude 3 Haiku',
        description: 'Fastest, most cost-effective model',
      },
      {
        id: 'claude-2:1',
        name: 'Claude 2.1',
        description: 'Previous generation model',
      },
    ],
  },
  {
    id: 'google',
    name: 'Google',
    baseURL: 'https://generativelanguage.googleapis.com/v1beta/openai/',
    requiresAuth: true,
    apiKeyEnvVar: 'GOOGLE_API_KEY',
    apiKeyEnvAliases: ['GEMINI_API_KEY'],
    icon: '🔍',
    description: "Google's Gemini models (OpenAI-compatible endpoint)",
    docsUrl: 'https://ai.google.dev',
    models: [
      {
        id: 'gemini-2.5-flash',
        name: 'Gemini 2.5 Flash',
        description: 'Fast Gemini 2.5 with strong coding',
        default: true,
      },
      {
        id: 'gemini-2.5-pro',
        name: 'Gemini 2.5 Pro',
        description: 'Higher-quality Gemini 2.5',
      },
      {
        id: 'gemini-2.0-flash',
        name: 'Gemini 2.0 Flash',
        description: 'Fast, efficient Gemini 2.0',
      },
      {
        id: 'gemini-1.5-pro',
        name: 'Gemini 1.5 Pro',
        description: "Google's advanced model with long context",
      },
      {
        id: 'gemini-1.5-flash',
        name: 'Gemini 1.5 Flash',
        description: 'Faster, more cost-effective model',
      },
    ],
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    baseURL: 'https://api.mistral.ai/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'MISTRAL_API_KEY',
    icon: '🌪️',
    description: "Mistral's models",
    docsUrl: 'https://mistral.ai',
    models: [
      {
        id: 'mistral-large-latest',
        name: 'Mistral Large (Latest)',
        description: 'Latest Mistral Large flagship model, 128k context',
        default: true,
      },
      {
        id: 'mistral-small-latest',
        name: 'Mistral Small (Latest)',
        description: 'Fast, cost-effective model, 32k context',
      },
      {
        id: 'codestral-latest',
        name: 'Codestral (Latest)',
        description: 'Coding-specialized model, 256k context',
      },
      {
        id: 'open-mistral-nemo',
        name: 'Open Mistral Nemo',
        description: 'Open-weight model with 128k context',
      },
      {
        id: 'ministral-8b-latest',
        name: 'Ministral 8B (Latest)',
        description: 'Efficient 8B parameter edge model',
      },
      {
        id: 'mistral-embed',
        name: 'Mistral Embed',
        description: 'Embedding model for text representations',
      },
    ],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    baseURL: 'https://api.cohere.ai/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'COHERE_API_KEY',
    icon: '✨',
    description: "Cohere's AI models",
    docsUrl: 'https://cohere.ai',
    models: [
      {
        id: 'command-r-plus',
        name: 'Command R+',
        description: 'Advanced model with tool use',
        default: true,
      },
      {
        id: 'command-r',
        name: 'Command R',
        description: 'Reasoning model',
      },
      {
        id: 'command',
        name: 'Command',
        description: 'General-purpose model',
      },
      {
        id: 'embed-english-v3.0',
        name: 'Embed English v3',
        description: 'Embedding model',
      },
    ],
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    baseURL: 'https://openrouter.ai/api/v1',
    requiresAuth: true,
    apiKeyEnvVar: 'OPENROUTER_API_KEY',
    icon: '🌐',
    description: 'OpenRouter API - Access 300+ models through a unified API',
    docsUrl: 'https://openrouter.ai',
    dynamicModels: true,
    defaultRpm: 20,
    defaultMaxInFlight: 2,
    defaultHeaders: {
      'HTTP-Referer': 'https://github.com/leeno7786-coder/nanoagent',
      'X-Title': 'NanoAgent',
    },
    models: [], // Will be fetched dynamically from OpenRouter API
  },
];
